[package]
name = "awol"
version = "0.1.0"
authors = ["Nicole Tietz-Sokolskaya <me@ntietz.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
